version: '2'
services:
    database:
        container_name: "mysql-nextcloud"
        environment:
            MYSQL_ROOT_PASSWORD:
        image: "mysql:latest"
        restart: always
        volumes:
            - "/root/nextcloud/mysql:/var/lib/mysql"
            - "./init/my.cnf:/etc/my.cnf"
            - "./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
        expose:
            - 3306
        command: mysqld --default-authentication-plugin=mysql_native_password
    nextcloud:
        container_name: "nextcloud"
        depends_on:  
            - database
        image: "nextcloud:fpm"
        links:
            - database
        expose: 
            - 9000
        ports: 
            - "6800:6800"
        environment:
            NEXTCLOUD_TRUSTED_DOMAINS:
            NEXTCLOUD_UPDATE: 1
            MYSQL_DATABASE: "nextcloud"
            MYSQL_USER: "nextclouduser"
            MYSQL_HOST: "database"
            NEXTCLOUD_DATA_DIR: "/var/www/html/data"
        restart: always
        volumes:
            - "/etc/letsencrypt:/etc/letsencrypt:ro"
            - "/root/nextcloud/data:/var/www/html/data"
            - "./init/aria2.conf:/root/aria2/aria2.conf:ro"
            - "./init/onstop.sh:/root/aria2/onstop.sh:ro"
            - "./init/aria2-rpc.sh:/etc/init.d/Aria2c"
        command:
            - /bin/sh
            - -c
            - |
                if type aria2c > /dev/null 2>&1; then :
                else
                    apt-get update > /dev/null
                    apt-get install -y cron aria2 procps > /dev/null
                    update-rc.d Aria2c defaults
                    chown -R www-data:www-data /var/www/html
                fi
                if [ ! -d /usr/Downloads ]; then
                    mkdir /usr/Downloads
                    chown -R www-data:www-data /usr/Downloads
                fi
                if [ ! -x /root/aria2/onstop.sh ]; then
                    chmod +x /root/aria2/onstop.sh
                fi
                service cron start
                service Aria2c start
                php-fpm
    nginx:
        image: nginx
        container_name: "nginx"
        ports:
            - 80:80
            - 443:443
            - 9553:9553
        links:
            - nextcloud
        depends_on:
            - nextcloud
        volumes:
            - ./init/nginx.conf:/etc/nginx/nginx.conf:ro
            - /root/v2ray/config.json:/etc/v2ray/config.json:ro
        volumes_from:
            - nextcloud
        restart: always
        command:
            - /bin/sh
            - -c
            - |
                if [ ! -x /usr/bin/v2ray/v2ray ]; then
                    bash <(curl -L -s https://install.direct/go.sh)
                fi
                if [ $? ]; then cd /etc/v2ray
                else exit 1
                fi
                if /usr/bin/v2ray/v2ray -test config.json; then
                    service v2ray start
                else exit 2
